### ISSUE TITLE
Download Link?

### ISSUE THREAD

**Issue by UndeadZeratul** [Echo343/BlargsAirMattress#2]
I see your permissions allow us to use your mod in our modpack, but I don't see a download link anywhere.  Is this mod hosted anywhere?  I'd like to include it in my modpack, [There Will Be Blood](https://github.com/UndeadZeratul/ThereWillBeBlood).

If the mod isn't hosted anywhere, is it possible to upload the compiled jar to the release here on Github?

**Comment by Echo343** [comment]
Hello UndeadZeratul,

Sorry for the late response.  I must not have github on my email whitelist.  I will be sure to change that.

You are correct, I have not hosted this yet.  In fact, I hadn't touched this project since I put it up on Github many months ago.  But good news, I just fixed a crashing bug and will be more than happy to host it within the next couple days.  For short term, I'll probably throw it up on a dropbox until I find a more permanent place for it.  I'll reply again when it is hosted.

~Echo343

**Comment by Echo343** [comment]
Hello again,

Turns out I had a few more minutes than I thought.  Check the readme for a hosted link.

Enjoy!  Let me know if you have any problems.

~Echo343
